# Generated by Django 5.0.7 on 2024-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_number", models.IntegerField(unique=True)),
                ("problem_text", models.TextField()),
                (
                    "problem_image",
                    models.ImageField(blank=True, null=True, upload_to="problems"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
