# Generated by Django 5.0.7 on 2024-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_problems_delete_userinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problems",
            old_name="problem_text",
            new_name="animals_info",
        ),
        migrations.RemoveField(
            model_name="problems",
            name="problem_image",
        ),
        migrations.AddField(
            model_name="problems",
            name="animals_name",
            field=models.CharField(default="Unnamed", max_length=100),
        ),
        migrations.AddField(
            model_name="problems",
            name="animals_origin_image",
            field=models.ImageField(blank=True, null=True, upload_to="problems/origin"),
        ),
        migrations.AddField(
            model_name="problems",
            name="animals_skeleton_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="problems/skeleton"
            ),
        ),
    ]
