# Generated by Django 5.0.7 on 2024-09-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_rename_problem_text_problems_animals_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problems",
            name="problem_info",
            field=models.TextField(
                default="它有棕色和白色相间的条纹,后翅有大眼斑,这是一种警戒色,其功能就是在欺骗捕食者,让对方误认为正有一只大眼睛动物在凶狠地瞪着它们."
            ),
            preserve_default=False,
        ),
    ]
