# Generated by Django 5.0.7 on 2024-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_problems_problem_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="AnimalGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.CharField(max_length=100)),
                ("is_correct", models.BooleanField()),
            ],
        ),
    ]
